[package]
name = "mdbook-trunk-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.1"
mdbook = "0.4.34"
serde_json = "1.0.105"
