[book]
authors = ["poijnhy"]
language = "jp"
multilingual = false
src = "src"
title = "computations"

[build]
build-dir = "../out/book"

[preprocessor.katex]
after = ["links"]
inline-delimiter = { left = "\\(", right = "\\)" }
block-delimiter = { left = "\\[", right = "\\]" }

[preprocessor.trunk-build]
component-dir = "../component/"
trunk-out-dir = "../out/dist"
book-out-dir = "../out/book"

[output.html]
additional-css = ["css/turing_machine.css"]
