[package]
name = "logic_circuit_web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
logic_circuit_core = { workspace = true }
utils = { workspace = true }
wasm-bindgen = { workspace = true }

[lints]
workspace = true
