[package]
name = "recursive_function_web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
recursive_function_core = { workspace = true }
utils = { workspace = true }
wasm-bindgen = { workspace = true }

[lints]
workspace = true
