WHITESPACE = _{ " " | "\n" }
COMMENT_MULTILINE = _{ ("/*" ~ (!"*/" ~ COMMENT* ~ ANY)* ~ "*/") }
COMMENT_ONELINE = _{ "//" ~ (!"\n" ~ ANY)* ~ "\n" }
COMMENT = _{ COMMENT_MULTILINE | COMMENT_ONELINE }

symbol = { "-" | "_" }
name = @{ (ASCII_ALPHA | ASCII_DIGIT | symbol)+ }

number = @{(ASCII_DIGIT)+}
inc = {"inc" ~ number}
dec = {"dec" ~ number}
clr = {"clr" ~ number}
cop = {"cop" ~ number ~ number}
ifz = {"ifz" ~ number ~ "goto" ~ number}
code = {(inc | dec | clr | cop | ifz)+ ~ EOI}
