[package]
name = "component"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo = "0.8.0"
yew = { version = "0.20.0", features = ["csr"] }
recursive_function = { path = "../../../models/recursive_function" }
recursive_function_view = { path = "../../../view/recursive_function" }
turing_machine = { path = "../../../models/turing_machine" }
turing_machine_view = { path = "../../../view/turing_machine" }
recursive_function_to_turing_machine = { path = "../../../compile/recursive_function_to_turing_machine" }
lambda_calculus = { path = "../../../models/lambda_calculus" }
lambda_calculus_view = { path = "../../../view/lambda_calculus" }
recursive_function_to_lambda_calculus = { path = "../../../compile/recursive_function_to_lambda_calculus" }
