[[mount]]
url_prefix = "/wasm_bundle/"
source = ".repo/generated/build-wasm/"

[[mount]]
url_prefix = "/md-preview-assets/"
source = ".repo/generated/build-md-preview/"

[[plugin]]
name = "build-wasm"
runner = "command"
command = ["node", "./plugin/mount_model/build.mjs", "--clean"]
trigger = "manual"

[[plugin]]
name = "build-md-preview"
runner = "command"
command = ["node", "./plugin/md_preview/build.mjs", "--out-dir", "{OUTPUT_DIRECTORY}"]
trigger = "manual"

[[task]]
name = "build-wasm"
steps = ["build-wasm"]

[[task]]
name = "build-md-preview"
steps = ["build-md-preview"]

[[task]]
name = "build-all"
steps = ["build-wasm", "build-md-preview"]

[[policy]]
path = "docs/**"
GET = true
POST = true
PUT = true
DELETE = true

[[policy]]
path = "viewer/**"
GET = true

[[policy]]
path = "cli/**"
GET = true

[[policy]]
path = "models/**"
GET = true

[[policy]]
path = "utils/**"
GET = true

[[policy]]
path = "workspace_fs/**"
GET = true

[[policy]]
path = "**/*.md"
GET = true
POST = false
PUT = true
DELETE = false

[[policy]]
path = "*.md"
GET = true
POST = false
PUT = true
DELETE = false
