name = "computation"

[[plugin]]
name = "build-wasm"
runner = "command"
command = ["node", "./plugin/mount_model/build.mjs", "--clean"]
trigger = "manual"
mount = "/wasm_bundle/"

[[plugin]]
name = "build-md-preview"
runner = "command"
command = ["node", "./plugin/md_preview/build.mjs", "--out-dir", "{OUTPUT_DIRECTORY}", "--wasm-mount-url", "{MOUNT_BUILD_WASM}"]
trigger = "manual"
deps = ["build-wasm"]
mount = "/md-preview-assets/"

[[task]]
name = "build-wasm"
steps = ["build-wasm"]

[[task]]
name = "build-md-preview"
steps = ["build-md-preview"]

[[task]]
name = "build-all"
steps = ["build-wasm", "build-md-preview"]

[[policy]]
path = "/"
GET = true

[[policy]]
path = "test/"
GET = true

[[policy]]
path = "docs/"
GET = true
POST = true
PUT = true
DELETE = true

[[policy]]
path = "models/"
GET = true
POST = false
PUT = true
DELETE = false

[[policy]]
path = "viewer/"
GET = true

[[policy]]
path = "utils/"
GET = true

[[policy]]
path = "cli/"
GET = true

[[policy]]
path = "workspace_fs/"
GET = true

[[policy]]
path = "README.md"
GET = true
POST = false
PUT = true
DELETE = false

[[policy]]
path = "test.md"
GET = true
POST = false
PUT = true
DELETE = false
