[book]
authors = ["poijnhy"]
language = "jp"
multilingual = false
src = "src"
title = "computations"

[build]
build-dir = "../out/book"

[preprocessor.katex]
after = ["links"]
inline-delimiter = { left = "\\(", right = "\\)" }
block-delimiter = { left = "\\[", right = "\\]" }
