package computation:web;

world model {
  export make: func(code: string, ainput: string) -> result<_, string>;
  export step: func(rinput: string) -> result<string, string>;
  export snapshot: func() -> result<string, string>;
  export restore: func(snapshot: string) -> result<_, string>;
  export render: func(snapshot: string) -> result<string, string>;
}

world compiler {
  export compile-code: func(input: string) -> result<string, string>;
  export encode-ainput: func(ainput: string) -> result<string, string>;
  export encode-rinput: func(rinput: string) -> result<string, string>;
  export decode-routput: func(output: string) -> result<string, string>;
  export decode-foutput: func(output: string) -> result<string, string>;
}
