[package]
name = "models_of_computation_component"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { workspace = true }
gloo = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }

utils = { path = "../../../utils"}

recursive_function = { path = "../../../models/recursive_function" }
recursive_function_view = { path = "../../../view/recursive_function" }
turing_machine = { path = "../../../models/turing_machine" }
turing_machine_view = { path = "../../../view/turing_machine" }
recursive_function_to_turing_machine = { path = "../../../compile/recursive_function_to_turing_machine" }
lambda_calculus = { path = "../../../models/lambda_calculus" }
lambda_calculus_view = { path = "../../../view/lambda_calculus" }
recursive_function_to_lambda_calculus = { path = "../../../compile/recursive_function_to_lambda_calculus" }
while_minus_lang = { path = "../../../models/while_minus_lang" }
while_minus_lang_view = { path = "../../../view/while_minus_lang" }
recursive_function_to_while_minus_lang = { path = "../../../compile/recursive_function_to_while_minus_lang" }
